- hosts: core_2_ww
  roles:
    - role: arubanetworks.aoscx_role
  gather_facts: false
  vars:
    interfaces:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
  tasks:
    - name: disable L3 interfaces 1/1/2,1/1/3,1/1/4, 1/1/5
      aoscx_l3_interface:
        interface: 1/1/{{ item }} 
        admin_state: up
      loop: "{{ interfaces }}"
      when: 1 < item < 6
