--- 
- 
  gather_facts: false
  hosts: access_1_sw
  roles: 
    - role: arubanetworks.aoscx_role
  vars:
    ansible_python_interpreter: /home/student/ansible_venv/bin/python3
  tasks: 
    - 
      aoscx_command: 
        commands: ["sh lldp neighbor-info","show mac-address-table"]
      register: command_output
      name: "Execute show lldp neighbor and show mac-addres-table"
    - 
      debug: 
        msg: "{{ command_output }}"
      name: "Print command output"